=== jluis-ll/40270/xml/gramatica.dtd
<!ELEMENT gramatica (regla*)>
<!ELEMENT regla (nombre, produccion+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT produccion (simbolo+)>
<!ELEMENT simbolo (#PCDATA)>

=== jluis-ll/40270/xml/gramatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gramatica SYSTEM "gramatica.dtd">

<gramatica>
    <regla>
        <nombre>S</nombre>
        <produccion>
            <simbolo>A</simbolo>
            <simbolo>B</simbolo>
        </produccion>
        <produccion>
            <simbolo>a</simbolo>
        </produccion>
    </regla>

    <regla>
        <nombre>A</nombre>
        <produccion>
            <simbolo>a</simbolo>
            <simbolo>A</simbolo>
        </produccion>
        <produccion>
            <simbolo>a</simbolo>
        </produccion>
    </regla>

    <regla>
        <nombre>B</nombre>
        <produccion>
            <simbolo>b</simbolo>
        </produccion>
    </regla>
</gramatica>
